name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Flutter Web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "master"

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: dart run build_runner build -d && dart run slang && flutter build web --release --base-href /6-semester-coursework/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /build/web
